### ISSUE TITLE
Proper versioning

### ISSUE THREAD

**Issue by ggardet** [myungjoo/SSAT#18]
Could we have a proper versioning? 
This would include some tags and associated tarballs. Also the version written in `ssat.sh` should be kept up-to-date: https://github.com/myungjoo/SSAT/blob/master/ssat.sh#L34

**Comment by myungjoo** [comment]
Sure, I'll update them.

**Comment by myungjoo** [comment]
PR #19 should've resolved it. Please take a look at it.

**Comment by ggardet** [comment]
> PR #19 should've resolved it. Please take a look at it.

This looks good, but a git tag + an archive for version  `1.2.0` would be perfect.

**Comment by myungjoo** [comment]
Release tag added along with archives: https://github.com/myungjoo/SSAT/releases/tag/v1.2.0
